CHANGELOG.md
app/scripts/actions/index.js
app/scripts/config/index.js
package.json

Addresses https://bugs.earthdata.nasa.gov/browse/CUMULUS-197
* Update version 1.0.0 -> 1.0.1
* Added a CHANGELOG.md
* Updated all api paths to go to v1 api endpoints
After merging, will add a version git tag.

Cumulus 197

---

app/scripts/components/logs/viewer.js

Added correct log level format
All logs coming from elastic search have {level: 30} instead of {level: 'info'}

Cumulus-561 

---

CHANGELOG.md
app/scripts/components/executions/execution-status.js
package.json

Add Link on execution page to parent workflow execution page (if parent execution arn exists in the input.cumulus_meta)

CUMULUS-689 Supply link to Parent workflow execution

---

CHANGELOG.md
fake-api.js

Last minute changes for Main page testing

Cumulus 638

---

cypress/integration/main_page_spec.js

Cumulus-640 Testing Log out of Dashboard

---

.eslintrc
app/scripts/components/form/text-area.js
app/scripts/components/workflows/workflow.js
app/scripts/utils/browser.js
cypress/integration/collections_spec.js
cypress/integration/workflows_spec.js
cypress/support/commands.js
cypress/support/commands.ts
test/fake-api-fixtures/workflows/index.json

* Add fake API fixture for workflows
* Add test for viewing workflows list in the dashboard

CUMULUS-647

---

cypress/fixtures/TESTCOLLECTION___006.json
cypress/fixtures/example.json
cypress/integration/collections_spec.js
cypress/integration/providers_spec.js

The tests for Editting provider and collection have been added under PR.
https://github.com/nasa/cumulus-dashboard/pull/498
This PR has minor updates.

CUMULUS-651: Edit provider and collection

---

README.md

Creating a hotfix PR for these changes since they are relevant to the current state of the `master` branch

Hotfix PR to master: Documentation updates

---

.circleci/config.yml
package.json
yarn.lock

circleci log should show the audit command and result.

add audit to circleci

---

app/scripts/components/app/add-raw.js
app/scripts/components/app/add.js
app/scripts/components/app/edit-raw.js
app/scripts/components/app/edit.js
app/scripts/components/app/login-modal.js
app/scripts/components/app/oauth.js
app/scripts/components/app/timer.js
app/scripts/components/collections/ingest.js
app/scripts/components/collections/overview.js
app/scripts/components/errors/report.js
app/scripts/components/form/async-command.js
app/scripts/components/form/batch-async-command.js
app/scripts/components/form/schema.js
app/scripts/components/logs/viewer.js
app/scripts/components/rules/rule.js
app/scripts/components/table/list-view.js
app/scripts/components/workflows/workflow.js

Removed all UNSAFE_componentWillReceiveProps

Cumulus-1097-2 Remove all unsafe methods

---

.circleci/config.yml

CUMULUS-1105
When merging to the deploy branch, deploy the dashboard to a sandbox bucket and a SIT bucket.

Workflow to deploy to Sandbox and SIT

---

CONTRIBUTING.md
README.md
app/scripts/reducers/pdrs.js
app/scripts/reducers/remove-deleted.js
package.json

See It Fix It PR updating links in documentation.
Changes:
* `s/cumulus-nasa/nasa/g`

Replace cumulus-nasa with nasa

---

CHANGELOG.md
README.md
app/scripts/components/app/oauth.js
app/scripts/config/config.js
app/scripts/config/index.js
app/scripts/main.js
bin/build_in_docker.sh

Adds optional configuration to use SAML protected Cumulus via Launchpad.
Adds REDUX Developer Tools to the build for debugging.

Update saml login API starting point.

---

app/scripts/components/collections/overview.js
app/scripts/components/locale.js

Added to Collections Page:
- Granule Name Search (works with full name, and substring IF string starts at beginning of name)
- Granule Status search
Did Not: 
- add the category search box because we do not have a category on granules yet. 
- match the design exactly because there's a styling ticket for that.

Cumulus-1503 Adding Granule Search

---

CHANGELOG.md
app/src/js/actions/index.js
package.json

Enabling/disabling was throwing schema validation errors, so fixed in this PR

Cumulus 1308 lauren

---

CHANGELOG.md
app/src/js/actions/index.js
app/src/js/components/Rules/overview.js
app/src/js/components/Rules/rule.js
package.json
test/fake-api/fixtures/schemas/rule/index.json

Handle rule rerun and bulk enable/disable

CUMULUS-1308

---

app/src/css/modules/_table.scss
app/src/js/components/Granules/progress.js

changing colors of failed granules count

Cumulus-1462 Update failed granules count color

---

app/src/js/App.js
app/src/js/components/Collections/granules.js
app/src/js/paths/collections.js

- added new routes in collections category for granule statuses 
- added granule status option to sidebar 
- added granule search to new granule status pages

1507 Collection - Individual - Granules 

---

.eslintrc
.markdownlint.json
CHANGELOG.md
app/src/js/components/DropDown/simple-dropdown.js
app/src/js/components/Logs/viewer.js
package-lock.json
package.json

Fix log search on granule detail page
On the granule detail page, when a user started typing in the
log search box, the UI broke and rendered a blank page due
to a React rendering "infinite loop."
CUMULUS-1679

Fix log search on granule detail page

---

cypress/integration/collections_spec.js
cypress/integration/executions_spec.js
cypress/integration/granules_spec.js

Selectors were still broken even though the buttons were correct.  These will find the buttons and pass the cypress tests.

Button style fix pr suggestion

---

app/src/js/reducers/operations.js

Fix from the 1690 PR bug that was _Entirely_ my fault. 
Fixed: clicking on a new page in the header from the operations page works.

UGHHH: removing nonsense code

---

app/src/js/config/config.js
app/src/js/utils/basic-auth.js
webpack.common.js

Re-adds in the config for Metrics' Elasticsearch, allowing the metrics numbers on the home page to show up correctly.

[CUMULUS-1467] Fix config for Metrics ES User/Password

---

CHANGELOG.md
app/src/js/config/index.js
package-lock.json
package.json

Release the dashboard.

---

README.md
app/src/js/config/config.js
app/src/js/store/configureStore.js
webpack.common.js
webpack.prod.js

Pull in master's hotfix for dashboard from cumulus API

Hotfix remerge

---

package-lock.json
package.json

merge master release back into develop.

Update master 1.7.1

---

CHANGELOG.md
app/src/js/components/Datepicker/Datepicker.js
app/src/js/components/Datepicker/Datepicker.scss
app/src/js/reducers/datepicker.js
app/src/js/utils/datepicker.js
cypress/integration/main_page_spec.js
test/reducers/datepicker.js
test/utils/datepicker.js

@jjmccoy 
This is a PR into your PR.  I merged your changes on top of #693 and then added the refresh functions to the datepicker.  
This would still be considered WIP. But should be a better place for you to keep tweaking if you want.

Cumulus 1798 mhs

---

app/src/js/actions/index.js
app/src/js/components/Granules/overview.js
app/src/js/components/Pdr/list.js
app/src/js/components/Pdr/overview.js
app/src/js/components/Pdr/pdr.js
app/src/js/components/home.js
cypress/integration/granules_spec.js

Add datetime params to the getCount API call.
Also adds 0 to overview when no data is available.

Cumulus 1796 bug with stats for getCount

---

CHANGELOG.md

Updates the changelog to reflect changes in CUMULUS-1467

[CUMULUS-1467] Update Changelog

---

CHANGELOG.md
app/src/css/_badges.scss
app/src/css/_base.scss
app/src/css/_lists.scss
app/src/css/_typography.scss
app/src/css/main.scss
app/src/css/vendor/bootstrap/_components.scss
app/src/js/components/Form/_form.scss
app/src/js/components/Rules/rule.js
app/src/js/components/Table/Metadata.js
cypress/integration/rules_spec.js
test/components/reconciliation-reports/reconciliation-report.js

Style how individual rule page will look and feel. Add the state "enabled" and "disabled" badge indicators and restyle the details table. The sidebar does not contain "enabled" and "disabled" because we do not have those subpages built out yet. Currently, working on the logic for showing "enabled" and "disabled" badges.

Cumulus 1527

---

CHANGELOG.md
app/src/css/_buttons.scss
app/src/js/actions/index.js
app/src/js/components/Add/add.js
app/src/js/components/Datepicker/Datepicker.js
app/src/js/components/Form/Form.js
app/src/js/components/Form/_form.scss
app/src/js/components/FormSchema/schema.js
app/src/js/components/Rules/add.js
app/src/js/utils/validate.js
cypress/integration/providers_spec.js
cypress/integration/rules_spec.js
package.json
test/components/form/edit-record.js

Changed "Add Rule" form from raw JSON input to form with individual fields.

CUMULUS-1528

---

cypress.json
cypress/integration/collections_spec.js
cypress/integration/executions_spec.js
cypress/integration/granules_spec.js
cypress/integration/providers_spec.js
cypress/integration/reconciliation_spec.js
cypress/integration/workflows_spec.js

I'm pretty certain, this link below is describing a bunch of problems we're
having.
You should read this whole thing, but the TL;DR:
"For a variety of implementation reasons, Cypress commands only retry the last
command before the assertion."
https://docs.cypress.io/guides/core-concepts/retry-ability.html#Only-the-last-command-is-retried

Fixes "obvious" selector problems.

---

package-lock.json
package.json

This updates to the latest alpha package based off of cumulus-core c7b4761cebadb061b318b4d7baf4327d487e4c72
I did see a test failure, but it's unrelated to this update.

Cumulus 1824 update local api version

---

README.md

Just links to the operator docs.

Note on where do find information on how to serve the dashboard.

---

app/src/js/actions/index.js

I have tested without this workaround in and this hack is no longer needed

Remove workaround that is no longer needed

---

CHANGELOG.md
app/src/css/_chart.scss
app/src/css/_normalize.scss
app/src/css/main.scss
app/src/js/components/Executions/execution-status-graph.js
app/src/js/components/Executions/index.js
cypress/integration/executions_spec.js
package-lock.json

So Far:
* Remove datepicker on execution overview and logs page

[CUMULUS-1813] Fix execution graph on Execution page

---

app/src/js/components/EditRaw/edit-raw.js
app/src/js/components/Modal/modal.js
app/src/js/components/Providers/provider.js
cypress/integration/collections_spec.js
cypress/integration/rules_spec.js

This ticket was originally for a bug where rule edits were silently ignored/not displaying an error for the user in the UI.
That seemed to be fixed already, so I updated some tests and made other tiny tweaks around the edit flow for various records.

[CUMULUS-1685] Edit rule tests

---

CONTRIBUTING.md
app/src/js/components/BatchAsyncCommands/BatchAsyncCommands.js
app/src/js/components/Errors/report.js
app/src/js/utils/format.js
cypress/integration/providers_spec.js

Fix typos contrib pgrimaud typobot

---

cypress/integration/providers_spec.js
package-lock.json
package.json

BLOCKED: Need to install cumulus/api v1.22.0 to work with this.
be sure to do the fancy uninstall cmrjs then reinstall at 1.11.0.

Fix typos in tests coming from Cumulus/api

---

CHANGELOG.md
app/src/js/config/index.js
package.json

tested against the api/dashboard endpoint on SIT
tested against cloudfront with and without SERVED_FROM_CUMULUS_API=true
Tested running locally against a live API

release 1.8.0

---

app/src/js/reducers/providers.js
app/src/js/reducers/utils/reducer-creators.js
cypress/fixtures/rule-error.json
cypress/fixtures/rule-success.json
cypress/integration/rules_spec.js
test/reducers/granules.js
test/reducers/providers.js
test/reducers/rules.js
test/reducers/utils/reducer-creators.js

Fixes CUMULUS-1988
Updates the reducer-creators to use safe methods not assuming that all values exist.
Adds tests for a small number of reducers as well as for the reducer-creators.

Fixes unsafe reducer-creators.

---

.eslintrc
app/src/js/components/Collections/add.js
app/src/js/components/Collections/edit.js
app/src/js/components/Collections/granules.js
app/src/js/components/Collections/index.js
app/src/js/components/Collections/ingest.js
app/src/js/components/Collections/list.js
app/src/js/components/Collections/logs.js
app/src/js/components/Collections/overview.js
app/src/js/components/Timer/timer.js
app/src/js/components/locale.js
package-lock.json
package.json

Sorry this is a combo of both prettier.io the Collection files *and* cleaning up the connect() calls 
I think all of the existing mapStateToProps that were `(state) => state` can cause undue rendering, so I removed unused parts of the state where appropriate.
eslintrc was updated because prettier forces no space between function and paren.  I set it all to ignore for now so that this didn't touch every file.

Mhs/cumulus 1869/pre work cleanup

---

audit-ci.json
package.json

skip http-proxy until a patch or new module is found.

whitelist http-proxy

---

CHANGELOG.md
app/src/js/config/index.js
package-lock.json
package.json

Release v1.9.0

---

cypress/integration/collections_spec.js

**Summary:** Fixes some intermittent test failures
* Add various waits on different requests to prevent failures

Fix collection spec failures

---

CHANGELOG.md
app/src/css/_buttons.scss
app/src/js/actions/index.js
app/src/js/components/ReconciliationReports/list.js
app/src/js/utils/table-config/reconciliation-reports.js
cypress/fixtures/seeds/reconciliationReportFixture.json
cypress/integration/reconciliation_spec.js

Addresses [CUMULUS-1918: Add delete button to Reconciliation Reports](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1918)

[CUMULUS-1918]Add delete button to Reconciliation Reports

---

CHANGELOG.md
README.md
app/src/js/components/Granules/index.js
app/src/js/components/Pdr/index.js
app/src/js/components/Pdr/list.js
app/src/js/components/Pdr/overview.js
app/src/js/components/QueryWrapper/query-wrapper.js
app/src/js/utils/table-config/pdr-progress.js
app/src/js/utils/table-config/pdrs.js
cypress/fixtures/seeds/pdrsFixture.json
cypress/integration/pdrs_spec.js
cypress/plugins/seedEverything.js

Addresses [CUMULUS-1815: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1815)
* Fix PDR tables and remove extra timers
* Add breadcrumbs to PDR pages
* Refactor PDR Index component to use functional style

[CUMULUS-1815] Fix PDR tables

---

CHANGELOG.md
app/src/js/components/SortableTable/SortableTable.js
app/src/js/components/Workflows/overview.js
app/src/js/utils/table-config/executions.js
app/src/js/utils/table-config/granules.js
app/src/js/utils/table-config/rules.js
app/src/js/utils/table-config/workflows.js
babel.config.js
cypress/integration/collections_spec.js
cypress/integration/granules_spec.js
cypress/support/commands.js
package-lock.json
package.json

Addresses [CUMULUS-1842: Fix dashboard sort issue](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1842)
* `react-table` column `accessor` should be primitive and sortable.
* manual sort for `workflows` since workflows are not saved in elasticsearch and not searchable.

CUMULUS-1842: Fix dashboard sort issue

---

CHANGELOG.md
USAGE.md
app/src/js/actions/index.js
app/src/js/components/Executions/overview.js
app/src/js/components/Operations/overview.js
app/src/js/components/Table/Table.js
app/src/js/reducers/collections.js
app/src/js/reducers/executions.js
app/src/js/reducers/granules.js
app/src/js/reducers/operations.js
app/src/js/reducers/pdrs.js
app/src/js/reducers/providers.js
app/src/js/reducers/reconciliation-reports.js
app/src/js/reducers/rules.js
cypress/integration/granules_spec.js
package-lock.json
package.json

Addresses [CUMULUS-2019: Support partial search](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2019)
* Support partial search
* Add cypress test for the partial search

CUMULUS-2019: Support partial search

---

CHANGELOG.md
app/src/css/_base.scss
app/src/css/_legend.scss
app/src/css/main.scss
app/src/js/components/ReconciliationReports/index.js
app/src/js/components/ReconciliationReports/legend.js
cypress/integration/reconciliation_spec.js

**Summary:** Add legend to reconciliation report
Addresses [CUMULUS-1914: Reconciliation Reports - List - Construct "Legend" Section](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1914)
* Construct legend component
* Various style tweaks

CUMULUS-1914 Reconciliation Report Legend

---

CHANGELOG.md
app/src/css/_buttons.scss
app/src/css/modules/_table.scss
app/src/js/components/ReconciliationReports/list.js

Addresses [CUMULUS-1919: Reconciliation Reports - List - Style page](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1919)
* Added breadcrumbs
* Moved Create Report Button and updated styles
* Add report count section

CUMULUS-1919 Report list page style

---

CHANGELOG.md
app/src/js/components/Pdr/overview.js
app/src/js/components/Pdr/pdr.js
cypress/integration/granules_spec.js

Addresses [CUMULUS-1870: Fix Timers - Pdr pages](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1870)
* Fix timers on Pdrs page
* Fix cypress granules_spec.js granule sorting error

CUMULUS-1870:Fix timers on Pdrs page

---

CHANGELOG.md
app/src/js/components/Operations/overview.js
app/src/js/components/ReconciliationReports/list.js

Addresses [CUMULUS-1875: Fix Timers - Operations Page](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1875)
Addresses [CUMULUS-1877: Fix Timers - Reconcilation Reports page](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1877)

CUMULUS-1875-1877:Remove unecessary timers on Operations and Reconcilation Reports pages

---

package.json

This can't really save any time can it?
Well it looks like it's more than 12 minutes so....
**Summary:** Turn of saving videos on all tests.

don't make videos.

---

app/src/js/components/Header/header.js
app/src/js/paths/collections.js
app/src/js/paths/granules.js

Also searched for places where we followed the rule lodash/prefer-include

bad lint fix misordered headers.

---

CHANGELOG.md
app/src/js/components/home.js

Addresses [CUMULUS-1878: Fix Timers - Dashboard Home page](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1878)
* ...

CUMULUS-1878: Remove unnecessary timers on home page

---

app/src/js/actions/index.js
app/src/js/components/ReconciliationReports/report-heading.js
app/src/js/reducers/collections.js

**Summary:** three small changes
Addresses [CUMULUS-1961: Found working other tickets](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1961)
* Makes ranges in reconciliation reports include time and date in UTC
* Prevents later render error when action.data.results is undefined
* Rewords the API version warning to be more clear about which versions need to be updated.

Mhs/cumulus 1/fix random items

---

CHANGELOG.md
app/src/js/components/Executions/overview.js
app/src/js/components/Granules/overview.js
app/src/js/utils/table-config/executions.js

Addresses [CUMULUS-2023: Search Module: Filter Ordering](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2023)
* Update filter drop downs to have the same order as columns

CUMULUS-2023:Update filter drop downs to have the same order as columns

---

CHANGELOG.md
app/src/js/components/Collections/granules.js
app/src/js/components/Collections/list.js
app/src/js/components/Collections/overview.js
app/src/js/components/Executions/execution-events.js
app/src/js/components/Executions/overview.js
app/src/js/components/Form/_form.scss
app/src/js/components/Granules/list.js
app/src/js/components/Granules/overview.js
app/src/js/components/Operations/overview.js
app/src/js/components/Pdr/list.js
app/src/js/components/Pdr/pdr.js
app/src/js/components/ReconciliationReports/gnf-report.js
app/src/js/components/ReconciliationReports/inventory-report.js
app/src/js/components/ReconciliationReports/list.js
app/src/js/components/Rules/overview.js
app/src/js/components/Search/search.js
app/src/js/components/Workflows/overview.js
audit-ci.json

Addresses [CUMULUS-2022: Search Module: Character Limit Improvement](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2022)
* Improve search character limit
* whitelist node-forge until @cumulus/api @cumulus-cmrjs version updates

CUMULUS-2022: Improve search character limit

---

CHANGELOG.md
app/src/js/config/index.js
package-lock.json
package.json

Release 2.0.0

---

CHANGELOG.md
app/src/css/_chart.scss
app/src/css/modules/_table.scss
app/src/js/components/ReconciliationReports/create.js
app/src/js/components/Tooltip/tooltip.js
app/src/js/utils/format.js
app/src/js/utils/table-config/collections.js
app/src/js/utils/table-config/executions.js
app/src/js/utils/table-config/granules.js
app/src/js/utils/table-config/operations.js
app/src/js/utils/table-config/pdr-progress.js
app/src/js/utils/table-config/pdrs.js
app/src/js/utils/table-config/providers.js
app/src/js/utils/table-config/rules.js
app/src/js/utils/type.js

Addresses [CUMULUS-2091: Dashboard tooltip](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2091)
* Add Tooltip component
* Add blue tooltip for timestamp values in the table

CUMULUS-2091: Dashboard tooltip

---

CHANGELOG.md
app/src/js/config/index.js
package-lock.json
package.json

Release 3.0.0

---

CHANGELOG.md
app/src/js/components/Executions/execution-events.js
app/src/js/components/Executions/execution-status.js
app/src/js/utils/table-config/execution-status.js
cypress/integration/executions_spec.js
test/components/executions/execution-events.js

**Summary:** Update execution events input details
Addresses [CUMULUS-1895: Dashboard: Executions "More Details"](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1895)
* Replace Collapsible component with a modal to display input details for each event
* Make ExecutionEvents a function component

[CUMULUS-1895] Execution Events More Details Modal

---

CHANGELOG.md
app/src/css/_base.scss
app/src/css/vendor/bootstrap/overrides/_modal.scss
app/src/js/components/Form/Form.js
app/src/js/components/Form/_form.scss

Addresses [CUMULUS-2069: Dashboard: UI Button Groups](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2069)
* Standardize UI button groups

CUMULUS-2069: Standardize UI button groups

---

CHANGELOG.md
app/src/js/components/Form/Form.js
app/src/js/components/Form/_form.scss

Addresses [CUMULUS-2073: Dashboard: UI Requirement Indicator](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2073)
* Update forms with the required indicator and description

CUMULUS-2073 Update forms with the required indicator and description

---

CHANGELOG.md
app/src/js/components/SortableTable/SortableTable.js
cypress/integration/main_page_spec.js
cypress/integration/reconciliation_spec.js
package-lock.json
package.json

**Summary:** Fixed pagination bug
Addresses [CUMULUS-2322: Pagination in rec reports not working and causing page to rerender](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2322)
* Removed `<form>` wrapper from `SortableTable` so that button elements in pagination don't trigger a form submit. The form wrapper isn't doing anything so it's safe to remove.
* Also removed `node-notifier` so we can close out https://github.com/nasa/cumulus-dashboard/pull/912. We are no longer using this dependency so we can remove it.

[CUMULUS-2322] Pagination bugfix

---

CHANGELOG.md
app/src/css/_badges.scss
app/src/css/_base.scss
app/src/js/components/Executions/execution-status.js
app/src/js/components/Form/_form.scss
package-lock.json
package.json

Addresses [CUMULUS-2074: Dashboard: UI Fix - Executions](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2074)
* Changed execution status to use `status_badge` class
* Updated the `<dd>` to have `font-weight: 400`
* Update `axios` - was causing audit failure

[CUMULUS-2074] Execution details style updates

---

README.md

Update instructions for deploying to cloudfront.

---

CHANGELOG.md
README.md

Remind people to include a breaking changes part of the changelog
New step for merging back to develop after release
Also updates CHANGELOG for previous release

Additional instructions for future releases.

---

CHANGELOG.md
test/reducers/api-version.js

The property name (isCompatible) was incorrect.
From https://github.com/nasa/cumulus-dashboard/pull/938

Fix version compatibility test (#938)

---

README.md

**Summary:** Update README for current docker Config. 
Addresses [CUMULUS-2381: Developer Bootcamp improvements](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2381)
* README changes.
- [ n/a ] Update CHANGELOG
- [ n/a ] Unit tests
- [ n/a ] Adhoc testing
- [ n/a ] Integration tests

Update Docs to better reflect current docker build process.

---

CHANGELOG.md
app/src/js/config/index.js
package.json

**Summary:** dashboard release

Version bumps for release v5.0.0

---

README.md

Tweak docs to help with bamboo release.

---

CHANGELOG.md
localAPI/docker-compose-cypress.yml
package-lock.json
package.json

upgrade cypress to 7.0.1

---

CHANGELOG.md
package-lock.json
package.json

Updates versions for release v6.0.0

---

CHANGELOG.md
app/src/css/_base.scss
app/src/js/components/Footer/footer.js
audit-ci.json
cypress/integration/main_page_spec.js
test/components/footer/version.js

**Summary:** Updated Cumulus Dashboard Footer
Addresses [CUMULUS-2467: Dashboard: Footer Links](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2467)
* Added FOIA, Privacy, and Feedback links to the footer
* Modified layout of version of Cumulus Dashboard and API moving them into a single row centered in the footer
* Added link to Cumulus GitHub docs page

Cumulus 2467

---

audit-ci.json

This package is included via:
"@cumulus/api>@cumulus/cmr-client>public-ip>dns-socket>dns-packet",
"@cumulus/api>@cumulus/cmrjs>@cumulus/cmr-client>public-ip>dns-socket>dns-packet",
"@cumulus/api>@cumulus/cmrjs>public-ip>dns-socket>dns-packet"
**Summary:** Update audit whitelist.

Whitelist new vulnerability dns-packet

---

CHANGELOG.md
app/src/css/_base.scss
app/src/css/_buttons.scss
app/src/css/modules/_table.scss
app/src/js/components/Executions/overview.js
app/src/js/components/Form/_form.scss
app/src/js/components/Operations/overview.js
app/src/js/components/Rules/overview.js
app/src/js/components/Search/search.js
app/src/js/components/Table/TableFilters.js
app/src/js/components/Workflows/overview.js

Addresses [CUMULUS-2524: CSS Tweaks](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2524)
* CSS & UI tweaks to padding/margin, width, and color/contrast for the following:
- Home page sections
- Table search and filters
- Footer

Cumulus 2524 - CSS Tweaks

---

CHANGELOG.md
app/src/js/utils/format.js
cypress/integration/collections_spec.js
cypress/integration/executions_spec.js
cypress/integration/granules_spec.js
cypress/integration/pdrs_spec.js

Addresses [https://bugs.earthdata.nasa.gov/browse/CUMULUS-2544](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2544)
Swapped the values of tooltip and target so the tooltip now shows time elapsed since the target
Fixed regex check to account for full date and time, not looking for time elapsed
Fixed test checking for time

CUMULUS-2544

---

CHANGELOG.md
app/src/css/_buttons.scss
app/src/js/components/BatchAsyncCommands/BatchAsyncCommands.js
app/src/js/components/Errors/copy-to-clipboard.js
app/src/js/components/Errors/report.js

Added a copy button to errors pages so error can be copied and searched up on the internet
Addresses [CUMULUS-2534: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2534)
* Added a copy button to errors pages so error can be copied and searched up on the internet
* ...

CUMULUS-2534

---

CHANGELOG.md
app/src/css/vendor/datetimepicker/_dtpoverrides.scss
app/src/js/components/Datepicker/DatepickerRange.js

Addresses [CUMULUS-2553: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2553)
* first commit. fixed leading zeros issue on the date picker

CUMULUS-2553

---

CHANGELOG.md
app/src/js/components/Footer/footer.js
app/src/js/components/home.js

Addresses [CUMULUS-2579: React Footer Error Fix](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2579)
* Fixed React error with Footer

Cumulus 2579

---

CHANGELOG.md
app/src/css/modules/_modals.scss
app/src/css/vendor/bootstrap/overrides/_modal.scss
app/src/js/components/AsyncCommands/AsyncCommands.js
app/src/js/components/DeleteCollection/DeleteCollectionModal.js
app/src/js/components/Granules/granule.js
app/src/js/components/ProcessingModal/ProcessingModal.scss
app/src/js/components/Providers/provider.js
app/src/js/components/Rules/rule.js
app/src/js/utils/format.js
app/src/js/utils/table-config/collections.js
app/src/js/utils/table-config/granules.js
app/src/js/utils/table-config/pdrs.js
app/src/js/utils/table-config/rules.js
cypress/integration/granules_spec.js
cypress/integration/rules_spec.js

Addresses [CUMULUS-2358: Standardize the default modal type](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2358)
-Refactored various different modals to adhere to the StandardModal design presented in ticket 2358
-Changed styling for Modal components (title/body)

CUMULUS-2358

---

CHANGELOG.md
app/src/js/components/DeleteCollection/BatchDeleteConfirmContent.js
app/src/js/components/DeleteCollection/BatchDeleteWithGranulesContent.js
app/src/js/components/DeleteCollection/DeleteCollectionModal.js
app/src/js/utils/format.js
app/src/js/utils/table-config/pdrs.js

Addresses [CUMULUS-2360: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2360)
- Implemented Error Alert into Modal of different delete and remove buttons

CUMULUS-2360: warning modal first PR

---

CHANGELOG.md
bamboo/set-bamboo-env-variables.sh
bamboo/set-status.sh
package-lock.json
package.json

Addresses [CUMULUS-bugfixes: Can't deploy to SIT](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2576)
`set-bamboo-env-variables.sh` script updated to have all of the variables needed
to test and deploy the dashboard to SIT.
Bamboo modified to use script appropriately.
Before, the bamboo tasks had explicit translations done in SIT e.g.:
export ESROOT=${bamboo.SIT_ESROOT}
export ES_USER=${bamboo.SECRET_SIT_ES_USER}
export ES_PASSWORD=${bamboo.SECRET_SIT_ES_PASSWORD}
Now running `. set-bamboo-env-variables.sh` in a task will parse those to the correct
values.
SIT_ESROOT =>  ESROOT
SECRET_SIT_ES_USER} => ES_USER
SECRET_SIT_ES_PASSWORD => ES_PASSWORD
* Updates only the bamboo environment script
* Slips in an update to axios to fix a snyk error

Updates to set bamboo environments for SBX and SIT

---

CHANGELOG.md
app/src/js/config/index.js
package-lock.json
package.json

-------
**Summary:**  Changes for a dashbaord release.

Changes for a dashboard release.

---

CHANGELOG.md
README.md
TABLES.md

fixed typos.

---

CHANGELOG.md
app/src/js/config/index.js
cypress/integration/providers_spec.js
cypress/integration/rules_spec.js
package-lock.json
package.json

**Summary:** 
update versions to support Cumulus API v10

Updates for release-9.0.0

---

CHANGELOG.md
package.json

Release v10.0.0

---

CHANGELOG.md
package.json

release-v11.0.0

---

CHANGELOG.md

fix changelog entries for v11.0.0

---

CHANGELOG.md
audit-ci.json
package-lock.json
package.json

Release v12.1.0

---

CHANGELOG.md
README.md

CUMULUS-3509: Update changelog for v12.0.2 and backport instruction

---

CHANGELOG.md
package-lock.json
package.json

dashboard release v12.2.0

---

CHANGELOG.md
CONTRIBUTING.md
README.md

fixes #1161 
Addresses GitHub issue #1161 to improve onboarding instructions
* Updated README to make copyable commands actionable without editing.
* Updated CONTRIBUTING as per above

Doug newman documentation fixes

---

CHANGELOG.md
docker/Dockerfile

Addresses [CUMULUS-4008: Dashboard: As part of the React upgrade, the Docker compose file needs to be modified as well](https://bugs.earthdata.nasa.gov/browse/CUMULUS-4008)
* Updated Dockerfile with improved npm ci command

update Dockerfile with improved npm ci command
