nasa/cumulus-dashboard

CHANGELOG.md
app/scripts/components/logs/viewer.js
app/styles/_lists.scss

This changes logs on the dashboard to use `level` instead of `type` and updates the styles and view to account for the additional levels:

cumulus-306: update log.type to log.level

---

CHANGELOG.md
app/scripts/components/form/batch-async-command.js
app/scripts/components/table/list-view.js
package.json
test/components/form/batch-async-command.js
yarn.lock

This PR allows a bulk action to continue even if errors are encountered. d3-queue is replaced with a queue module that collects and returns all errors instead of bailing on the first one. Then to make the impact on the codebase as small as possible, the array of errors are combined into one error message to be shown in the ui.

CUMULUS-515: allow batch-async-command to collect multiple errors and continue with the queue

---

app/scripts/components/rules/add.js

1. When a rule is added, the rule should have default state `ENABLED`, otherwise, the state is not set currently.
2. A separate `cumulus` PR will be submitted to set the state of the rule to default value 'ENABLED' if the state is not provided in the request.

CUMULUS-856: The rule should have default state ENABLED

---

.circleci/config.yml
.eslintrc
app/scripts/main.js
cypress.json
cypress/integration/main_page_spec.js
cypress/integration/rules.spec.js
cypress/support/assertions.js
cypress/support/commands.js
cypress/validation-tests/main-page.js
test/fake-api-fixtures/providers/PODAAC_SWOT/index.json
test/fake-api-fixtures/rules/MOD09GQ_TEST_kinesisRule/index.json
test/fake-api-fixtures/rules/index.json

- Add test for attempting to access Rules page when not logged in
- Add test for viewing rules when logged in
- Add login command to easily simulate login across multiple tests
- Cypress recommends having one E2E test for login that performs the UI interaction for login, but [for subsequent tests to login programatically](https://docs.cypress.io/guides/references/best-practices.html#Organizing-Tests-Logging-In-Controlling-State)

CUMULUS-649

---

app/scripts/components/pdr/pdr.js

The PDR details view was broken because it imported the granules table-config rather than the pdr table-config. The granules table-config has bulk actions unsupported for the PDR view, so an error is thrown. This fixes the import.

use pdrs table-config for pdrs view

---

CHANGELOG.md
app/scripts/utils/table-config/granules.js

The AC says:
In the dashboard, when viewing the list of granules, hovering on a reingest button indicates that existing data will be overwritten
But I think it's better to add the warning message in the confirmation screen to be consistent with other buttons.
Also the `reingest` button by default is disabled, and only enabled when a granule is selected, so hovering over won't display message added.

CUMULUS-792: add warning message to granules `reingest` button

---

gulpfile.js
package.json
yarn.lock

We removed `gulp-useref` because it didn't seem to be used and it has a dependency on potentially insecure versions of `event-stream`. However, `gulp-useref` is used by the gulp build (`npm run build`), so re-adding it to fix the broken build process.
For now, we're using [selective dependency resolutions](https://yarnpkg.com/lang/en/docs/selective-version-resolutions/) from `yarn` to pin the `event-stream` dependency to `3.3.4`
Also had to replace `gulp-uglify` with `gulp-uglify-es` since the `@cumulus/cmrjs` dependency is written in ES6 and uglifying vendor packages in ES6 requires `gulp-uglify-es`

Re-add gulp-useref dependency

---

gulpfile.js
package.json
yarn.lock

Fixes incompatibility issues between the dashboard and `@cumulus/cmrjs:1.11.1`. Right now, the dashboard is locked to `@cumulus/cmrjs:1.11.0`, so these fixes aren't really necessary until if/when we update that dependency, but there's no harm in merging them now.
There is a corresponding PR for Cumulus core to make package updates necessary for compatibility:
https://github.com/nasa/cumulus/pull/796
The fixes in that PR will be released as `@cumulus/cmrjs:1.11.2`, so if/when we do update our `@cumulus/cmrjs` dependency we should go straight from `1.11.0` to `1.11.2`

CUMULUS-1098

---

app/scripts/middleware/request.js

@laurenfrederick also logs?
Adds logs that are by default collapsed, but can be opened to examine details about the error and requestAction.  I think this will be useful when we get more bad logs in the future.

Adds collapsed logs to output.

---

app/scripts/actions/helpers.js
app/scripts/actions/index.js
app/scripts/middleware/request.js
test/actions/helpers.js

I think this is clearer what is happening. One side effect is that we get really long (and useless) errors now when you can't connect to the API, but that could be fixed.
But you can see the cumulus api errors now in the console.
It also fixes random dashboard version nit-pick
Fixes catch

Cumulus 1456 mhs suggest

---

app/scripts/actions/helpers.js
app/scripts/actions/index.js
app/scripts/middleware/request.js
test/actions/helpers.js
test/middleware/request.js

Merged this PR to standardize the default error message from our API with the other error messages: https://github.com/nasa/cumulus/pull/1216
Before that, all the error messages that hit the default handler were being obscured.
Then did this update to make the dashboard work with what's coming back from express to show actual error messages.

CUMULUS-1456 Handle error messages from express

---

CHANGELOG.md
app/src/js/actions/index.js
app/src/js/reducers/providers.js
app/src/js/reducers/rules.js

Fixes https://bugs.earthdata.nasa.gov/browse/CUMULUS-1670
I have submitted this PR as a hotfix against the `master` branch so we can get this fix out to users of the dashboard ASAP and not necessarily have to merge everything from `develop` into `master`
I have tested this against running the full Cumulus API locally, but still want to double check against my deployed Cumulus API.

CUMULUS-1670: Fix provider update

---

app/src/js/components/FormSchema/schema.js
cypress/integration/providers_spec.js

Updates the Schema component to recognize 'integer' as a number field. This causes the global connection limit field to appear in the "Add Provider" form.

[CUMULUS-1738] Add provider form in dashboard is missing the global connection limit

---

cypress/fixtures/cmr.json
cypress/integration/collections_spec.js

Wait for those routes when testing MMT links.
Removes unused CMR fixture for TESTCOLLECTION.

Give each MMT link a waitable route.

---

.circleci/config.yml

Error snapshots weren't being saved because I was uploading the wrong path.

Save snapshots by using correct path.

---

app/src/js/actions/index.js
test/actions/datefilters.js

Use the state's current startDateTime and endDateTime when making calls to the
stats endpoint.
This will need an update to the stats endpoint to parse the dates properly.

[cumulus-1729] Wrap getStats action creator in a thunk to get current date params.

---

app/src/js/components/Header/header.js
app/src/template.html

Fix paths for logo and favicon
* Logo: if `graphicsPath` does not have a trailing slash, we need to add one.
* Favicon: made this an absolute path by adding `/`

Fix pathing for logo and favicon

---

README.md
app/src/js/config/config.js
app/src/js/store/configureStore.js
webpack.common.js
webpack.dev.js
webpack.prod.js

This PR:
1. Sets the path to webpack bundles to be relative.
2. Adds new optional environmental variable `SERVED_BY_CUMULUS_API` that when set, will build a Cumulus dashboard configured with a hashHistory that allows the app to be served from a single endpoint.

Add configuration for building dashboard to be served by the cumulus API

---

cypress/integration/executions_spec.js
cypress/integration/granules_spec.js

I'm not sure if these are actually important, but this will at least test them
again.

Suggest: add back tests for values in granule overview

---

app/src/js/components/Collections/granules.js
app/src/js/components/Collections/list.js
app/src/js/components/Collections/overview.js
app/src/js/components/DropDown/dropdown.js
app/src/js/components/Search/search.js

This fixes the issue where submitting the dropdown input causes the page to reload with a `?` appended to the url.
Additionally, while working on this, I found when submitting the search input, it would clear whatever was typed.
In both cases, setting the `onSubmit` function for the wrapping form to only call `e.preventDefault()` resolved the issues.
Also in this PR, I added/updated the placeholders for the inputs on the Collections pages.

[CUMULUS-1621] Prevent page reload when pressing enter in dropdown

---

app/src/js/components/home.js
cypress/integration/main_page_spec.js
package-lock.json
package.json
test/components/table/list-view.js

(update base branch after #674 is merged)
Changes:
1. Updates localAPI to use alpha version of @cumulus/api to include the changes to ths stats endpoints.
2. Changes the query generated for the table filtering from an elastic querystring e.g. `q:'__exists__:error AND status:failed'` into a query object that is parsed by the stats/es search.  (note: If a request's query params include `&q=` only that query is used and everything else is ignored)
3. Datepicker changes dispatch a listGranules even with the correct filters.
4. Tests now check that the Granules Errors table has errors on load, and they disappear when you choose a date for filtering.

Cumulus 1468 datepicker changes trigger granule updates

---

webpack.common.js

In [`app/src/js/config/config.js`](https://github.com/nasa/cumulus-dashboard/blob/v1.7.1/app/src/js/config/config.js#L7), the key is "PDRs", not "pdrs".
This resolves the following warning presented during an `npm run build` when
`HIDE_PDR` is not set as part of the environment:
WARNING in EnvironmentPlugin - HIDE_PDR environment variable is undefined.
I encountered this warning while working through the [Deploy Cumulus Dashboard](https://nasa.github.io/cumulus/docs/deployment/deployment-readme#deploy-cumulus-dashboard) instructions.

webpack environment: fix the default value lookup for HIDE_PDR

---

CHANGELOG.md
app/src/js/components/Collections/edit.js
app/src/js/components/EditRaw/edit-raw.js
app/src/js/components/Rules/edit.js
cypress/integration/collections_spec.js
cypress/integration/rules_spec.js

Adds a confirmation modal when editing a rule.
Also, updated edit-raw.js to have default modal content where we swap in the record type and name, since content otherwise shouldn't change. This simplifies the edit collection component.
To test:
Verify edit rule has a confirmation modal indicating success or error.
Verify edit collection still works as expected

[CUMULUS-1535] Add confirmation modal for editing a rule

---

app/src/js/components/Datepicker/Datepicker.js

Lets react-datetime-picker return null correctly for clearing each datepicker with the X symbol.

Handle null return from react-datetime-picker.

---

CHANGELOG.md
app/src/js/actions/datepicker.js
app/src/js/actions/index.js
app/src/js/components/Datepicker/Datepicker.js
app/src/js/components/Datepicker/Datepicker.scss
app/src/js/reducers/datepicker.js
app/src/js/utils/datepicker.js
cypress/integration/main_page_spec.js
test/reducers/datepicker.js
test/utils/datepicker.js

This updates the functionality of the Datepicker and stats endpoints.
- Datepicker now defaults to "Recent" data when loading the dashboard.
- The Clear selection button resets both start and end datetimes and brings you to the "Custom" dropdown.
- URL params will load the correct dropdown values.
- tests added

Cumulus 1790 Update stats to work with datepicker

---

package.json
webpack.common.js

We already have a lint to prevent badly linted code to production. So this will
save frustration during devlopment.
:raised hands:

Switch eslint-loader to warnings.

---

README.md
cypress/integration/main_page_spec.js

With the addition of integration tests for metrics on the home page, the setup to pass tests for cypress changed a little. This updates the ENV vars needed to run the dashboard to get the cypress tests to pass.

[CUMULUS-1467] Update README for cypress tests metrics config

---

app/src/js/components/Edit/edit.js
cypress/integration/providers_spec.js

Fixes the issue with edit providers not redirecting back to overview on success. ComponentDidUpdate was using the previous state instead of the newly updated one

Fix EditRecord update behavior

---

app/src/js/components/Datepicker/Datepicker.js
app/src/js/reducers/assign-date.js
app/src/js/reducers/datepicker.js
app/src/js/reducers/dist.js
app/src/js/reducers/logs.js
app/src/js/reducers/workflows.js
app/src/js/utils/datepicker.js
app/src/js/utils/kibana.js
test/actions/datefilters.js
test/reducers/dist.js
test/reducers/stats.js
test/utils/datepicker.js
test/utils/kibana.js

Changes application state from Date Objects to Numbers that represent milliseconds since the Unix Epoch. Jan 1 1970, the value that is given by Date.now().  Or (new Date()).valueOf().

Cumulus 1796 fix datepicker state dates

---

cypress/integration/granules_spec.js

I'm pretty certain, this link below is describing a bunch of problems we're
having.  I have been unable to recreate the failed test since switching the get
selector.
Everyone should read this whole thing, but the TL;DR:
"For a variety of implementation reasons, Cypress commands only retry the last
command before the assertion."
https://docs.cypress.io/guides/core-concepts/retry-ability.html#Only-the-last-command-is-retried

Fix selector in spec to remove wait().

---

CHANGELOG.md
app/src/css/modules/_modals.scss
app/src/js/components/Executions/execution-status.js
app/src/js/components/Form/_form.scss
app/src/js/components/Granules/granule.js
app/src/js/components/Pdr/pdr.js
app/src/js/components/Providers/provider.js
app/src/js/components/ReconciliationReports/reconciliation-report.js
app/src/js/components/Rules/rule.js
app/src/js/components/Table/Metadata.js
cypress/integration/executions_spec.js
test/components/reconciliation-reports/reconciliation-report.js

This updates the execution status page to allow the user to view and download the full execution output.
Also, reworked the Metadata component so that it takes in an array of objects rather than an array of arrays so that it is easier to understand. Updated all instances where that component is being used. Pulled it into the executions page for use there as well.
There's limited styling, the rest should be applied in [CUMULUS-1538](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1538)

[CUMULUS-1537] View and download execution output

---

app/src/js/components/Operations/overview.js
app/src/js/reducers/workflows.js

This probably wasn't caught because we don't have tests for this page, that should probably get fixed.
Error:
Uncaught TypeError: Cannot assign to read only property 'data' of object '#<Object>'
at OperationOverview.render (VM452 bundle.js:274695)
at finishClassComponent (VM452 bundle.js:212676)
at updateClassComponent (VM452 bundle.js:212626)
at beginWork (VM452 bundle.js:214136)
at HTMLUnknownElement.callCallback (VM452 bundle.js:195704)
at Object.invokeGuardedCallbackDev (VM452 bundle.js:195753)
at invokeGuardedCallback (VM452 bundle.js:195808)
at beginWork$1 (VM452 bundle.js:218719)
at performUnitOfWork (VM452 bundle.js:217670)
at workLoopSync (VM452 bundle.js:217646)
at performSyncWorkOnRoot (VM452 bundle.js:217272)
at VM452 bundle.js:206605
at unstable_runWithPriority (VM452 …

Quick fix to keep from mutating state outside of a reducer.

---

app/src/js/actions/index.js
app/src/js/components/Collections/list.js
app/src/js/components/Rules/add.js
app/src/js/components/locale.js

1. When time filter is applied, header on collections page says "Active Collections". Otherwise, it says "All Collections". Also cleaned up some extraneous code on that page.
2. Removes time filter from the `listCollections` and `listProviders` actions on the Add Rule page by passing in `listAll` option
Can test by setting date to a time after data was seeded/ingested. When adding a rule, all collections and providers should still be populated. Did not change the workflows action since it does not take in a timefilter.

CUMULUS-1787 collections header

---

CHANGELOG.md
app/src/js/components/BatchAsyncCommands/BatchAsyncCommands.js
app/src/js/components/Collections/overview.js
app/src/js/components/Executions/execution-status-graph.js
app/src/js/components/ReingestGranules/BatchReingestCompleteContent.js
app/src/js/components/ReingestGranules/BatchReingestConfirmContent.js
app/src/js/utils/table-config/granules.js
cypress/integration/collections_spec.js
cypress/integration/granules_spec.js
cypress/integration/main_page_spec.js
package-lock.json
package.json
test/components/ReingestGranules/BatchReingestCompleteContent.js
test/components/ReingestGranules/BatchReingestConfirmContent.js
test/utils/table-config/granules.js

- Updates the modal workflow for a reingest action on the granule page.
+ When there is a single granule reingested, on complete action the user is redirected to that granule's overview page.
+ When multiple granules are ingested the complete action redirects the user to the granule's running page `/granule/processing`
- Adds reingest bulk action to the collections overview page with same behavior as for the granules page.

Cumulus 1677 modal workflow updates

---

app/src/js/actions/index.js
app/src/js/components/Collections/edit.js
cypress/integration/collections_spec.js

**Description of bug:** When editing the name or version of a collection, there is an error in the console, but it is not displayed in the modal or error message banner
**Solution:** This was happening because the request to `updateCollection` was using the name and version from the payload, regardless of the original collection the user is trying to edit. This causes the request to 404, since that new collection does not exist.
Additionally, in the redux state, that new collection id would be added to `collections.updated` instead of the id of the original collection.  `EditRaw` attempts to grab the error from `collections.updated[ORIGINAL COLLECTION ID]`, but it is undefined, since the request went to the new collection. Instead, `collections.updated[NEW COLLECTION ID]` is defined.
To …

[CUMULUS-1767] Fix lack of error messaging when attempting to update collection name or version

---

app/src/js/components/home.js

This fixes ~a number~ of timer bugs. (update: fixes CUMULUS-1811)
I will add the tickets as I verify them.
What was happening is that the componentWillMount was setting the cancelInterval function on this.cancelInterval without checking to see if one already existed and canceling that one.  The datepicker uses refreshQuery to do the same thing.  So sometimes this.cancelInterval was overwritten leaving an interval in place, when the user navigated to other pages, this interval would kick off unexpectedly causing update of granule data and causing the table to get rerended with unexpected data.

Prevents accidental overwrite of this.cancelInterval

---

app/src/js/reducers/granules.js

Since the reducer was directly setting `state.list`, any changes to the state were overridden. Also, any changes to `state.list.params` were overridden because it was set to an empty object. Updated the reducer to use the spread operator so that it can maintain the full `state.list` object.

Fix bug in dropdowns on granules page

---

app/src/js/components/Form/_form.scss
cypress/integration/collections_spec.js

The test is failing because once the date picker is clear, `listCollections` is called with no options. Then, before Cypress can actually click the correct item in the table, the timer dispatches `listCollections` with the correct options and changes the order. It then clicks the wrong item and the rest of the test fails.
This workaround simply stops the timer before clearing the date so that the order will remain the same when the click occurs.

Workaround to resolve intermittent failure in collection_spec

---

app/src/js/actions/index.js
app/src/js/components/Collections/overview.js
app/src/js/components/Overview/overview.js
app/src/js/components/Timer/timer.js
cypress/integration/collections_spec.js
test/actions/recover.js

Connects datepicker state to the timer the timer and now will the timer will refresh on datepicker changes.
Adds datepicker params to the getCollection call to Cumulus API so that the correct statistics show up when a page is filtered by the datepicker.
Adds cypress `data-cy` selector to overview for testing.
after this PR all of these items will have been addressed.
Fixes: https://bugs.earthdata.nasa.gov/browse/CUMULUS-1869

Mhs/cumulus 1869/fix granule metrics tiles

---

CHANGELOG.md
app/src/js/components/ReconciliationReports/list.js
app/src/js/components/SortableTable/SortableTable.js
app/src/js/components/Table/Table.js
app/src/js/reducers/reconciliation-reports.js
app/src/js/utils/format.js
app/src/js/utils/table-config/reconciliation-reports.js
cypress/integration/reconciliation_spec.js
test/reducers/reconciliation-reports.js

This adds additional columns to the list reconciliation reports page. This requires the new API to display the correct information.
Also some slight tweaks to the table sorting.

[CUMULUS-1916] Update reconciliation report columns

---

CHANGELOG.md
app/src/js/components/Granules/overview.js
cypress/integration/granules_spec.js
test/components/granules/overview.js

So Far:
* Change the Granule CSV Download. Before it would constantly refresh the CSV data in the background, which could take 1.5s with ~5000 granules. Now the data isn't updated until the user clicks the button.

[CUMULUS-1888] Granule Pagination improvements

---

CHANGELOG.md
cypress/fixtures/seeds/reconciliation-reports/inventoryReport-20200114T202529026.json
cypress/fixtures/seeds/reconciliation-reports/inventoryReport-20200114T205238781.json
cypress/fixtures/seeds/reconciliationReportFixture.json
cypress/integration/auth_spec.js
cypress/integration/reconciliation_spec.js
cypress/plugins/seedEverything.js
package-lock.json
package.json

**Summary:** Updates localAPI database seeding to work with (presumed) cumulus v1.22.0 release that includes recent updates to the reconciliation reports. 
Addresses [CUMULUS-1916](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1916)
* moved and renamed sample reconciliation reports from `@cumulus/api/app/data/reconciliation-reports` to cypress/fixtures/seeds/reconciliation-reports
* adds a reconciliation report record fixture
* uploads s3 reconciliation report files to correct locations.

Mhs/cumulus 1916/seed reconcilation reports

---

CHANGELOG.md
app/src/js/actions/index.js
app/src/js/components/ReconciliationReports/index.js
app/src/js/components/locale.js
test/actions/datefilters.js

Addresses [CUMULUS-1913: Add datepicker to Reconciliation Reports](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1913)

CUMULUS-1913: Add datepicker to Reconciliation Reports

---

CHANGELOG.md
app/src/css/_buttons.scss
app/src/css/modules/_table.scss
app/src/js/components/ReconciliationReports/reconciliation-report.js
app/src/js/components/SortableTable/SortableTable.js
app/src/js/components/Table/TableFilters.js
cypress/integration/reconciliation_spec.js
package-lock.json
package.json
test/components/table/TableFilters.js

**Summary:** Adds TableFilters component for dynamically hiding/showing columns in reconciliation reports view
Addresses [CUMULUS-1904: Reports: Inventory View - Table Advanced Column Filters](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1904)
* Updates react-table
* Uses `toggleHideColumn` function from the table instance to toggle the columns that are checked
* Various styles to match mock up

[CUMULUS-1904] Add TableFilters component

---

CHANGELOG.md
app/src/js/components/Executions/execution-events.js
app/src/js/components/Executions/execution-status.js
app/src/js/components/Executions/index.js
app/src/js/components/Executions/overview.js
app/src/js/components/Granules/list.js
app/src/js/components/Granules/overview.js
app/src/js/components/Operations/overview.js
app/src/js/components/Pdr/pdr.js
app/src/js/reducers/collections.js
app/src/js/reducers/granules.js
app/src/js/selectors/index.js
app/src/js/utils/table-config/executions.js
app/src/js/utils/table-config/pdr-progress.js
app/src/js/utils/table-config/pdrs.js
test/components/granules/overview.js

**Summary:** Fixes timers on the executions page. Also updates the collections dropdown on that page
Addresses [CUMULUS-1873: Fix Timers - Executions Page](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1873)
* Normalized props destructuring on executions pages
* Removed queryMeta interval from overview page. Also stopped it from dispatching `getMMTLinks`
* Updated collections dropdown on executions page
* This involved nixing the `collectionOptions` function and instead grabbing the options from the state as is happening on other pages. Moved this from the granules to collections reducer so that it made more sense when used on various pages, i.e. options are now in `state.collections.dropdown`
* When doing this, noticed pdr.js wasn't rendering, so had to swap `params` for `match.params` …

CUMULUS-1873 Executions page timers

---

CHANGELOG.md
app/src/js/components/Rules/add.js

**Summary:**
Addresses [CUMULUS-2024: Adding new provider or collection does not show in drop-down list when creating new rule](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2024)
The issue was caused by dispatching listCollections, listProviders, and listWorkflows in a single useEffect. The original workaround was to just check if they had already been dispatched, but this prevents a dispatch on initial render if they have already been dispatched on other pages, so we're not getting the freshest data. Removing the `if` statements causes issues because each dispatch causes the component to rerender, so there would be an infinite loop. Instead, we should put them each in their own useEffect. Since `dispatch` is the only dependency and it doesn't change between renders, it will only …

CUMULUS-2024 Dispatch providers and collections on AddRule initial render

---

CHANGELOG.md
app/src/js/components/Pagination/simple-pagniation.js
app/src/js/components/SortableTable/SortableTable.js

**Summary:** Add logic so not all pages are shown
Addresses [CUMULUS-2040: Update simple pagination to not display all page numbers when there are a large number of pages](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2040)
* Added logic to check if a page number falls with in the desired range that we want to display.
* If it doesn't, for the first instance, we add `...`, otherwise, we just return nothing
Easy way to test if you don't have a lot of conflicts:
In `SortableTable,js`, add `pageSize: 1` to the initialState that passed to `useTable` (line 95)
It would look like this:
```
initialState: {
hiddenColumns: initialHiddenColumns,
pageSize: 1
}
```
Then, go to `http://localhost:3000/reconciliation-reports/report/inventoryReport-20200114T202529026` and click the CMR tab, which has 15 …

CUMULUS-2040 Fix rec report pagination

---

CHANGELOG.md
webpack.dev.js

Addresses [CUMULUS-1830: Logging out when viewing a reconciliation report doesn't redirect you to the auth page, but just drops an error](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1830)
* Fix redirect issue when logging out from the page with URL path containing dot

CUMULUS-1830:Fix redirect issue when logging out

---

CHANGELOG.md
app/src/css/modules/_table.scss
app/src/js/actions/index.js
app/src/js/actions/types.js
app/src/js/components/Collections/overview.js
app/src/js/components/Executions/index.js
app/src/js/components/Executions/overview.js
app/src/js/components/Granules/index.js
app/src/js/components/Granules/overview.js
app/src/js/components/Operations/overview.js
app/src/js/components/Overview/overview.js
app/src/js/components/Pdr/index.js
app/src/js/components/Pdr/overview.js
app/src/js/components/Providers/overview.js
app/src/js/components/ReconciliationReports/index.js
app/src/js/components/ReconciliationReports/list.js
app/src/js/components/Table/Table.js
app/src/js/components/home.js
app/src/js/reducers/stats.js
cypress/integration/collections_spec.js
cypress/integration/granules_spec.js
cypress/integration/pdrs_spec.js

Addresses [CUMULUS-2029: Overview cards do not match what is displayed in the table](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2029)
* Updated how stats reducer shims in empty count values.
* Added a reducer for storing the count to be used in the sidebar separately. That way, the sidebar will always represent the unfiltered count
* Updated the Overview component so it dispatches the filtered count instead of having the items to display passed in.
* Updated `getCount` calls so they include query params

CUMULUS-2029 Update overview tiles to match what is displayed in table

---

ava.config.cjs
package-lock.json
package.json
test/actions/helpers.js
validation-tests.config.cjs

elliptical could be fixed in place with the suggested .
dot-prop required ava upgrade to 3.11
as a result two tests had to be updated.

release v1.10.0 redux : fix elliptical and dot-prop security fixes.

---

.circleci/config.yml

Acked-by: Matt Savoie <savoie@nsidc.org>
**Summary:** Disable deploy job (with belts and suspenders disabling the actual rsync) to prevent merges to develop from writing to the SIT bucket for Lauren's demo.

Disables push to SIT to keep demo smooth.

---

cypress/integration/main_page_spec.js

**Summary:** fix tests.
Addresses [CUMULUS-417: eslint](https://bugs.earthdata.nasa.gov/browse/CUMULUS-417)

cy.route was applied after visiting the page, so no stubs were found

---

CHANGELOG.md
app/src/js/utils/table-config/reconciliation-reports.js
cypress/integration/reconciliation_spec.js

Addresses [CUMULUS-2114: Internal-Consistency report can be generated from the dashboard](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2114)
* Add download button to the Internal report link
* CUMULUS-2087 was merged to create an Internal Report

CUMULUS-2114: Add download button to the Internal report link

---

CHANGELOG.md
app/src/css/_base.scss
app/src/js/components/ReconciliationReports/gnf-report.js
app/src/js/components/ReconciliationReports/report-heading.js
cypress/integration/reconciliation_spec.js

Addresses [CUMULUS-2086: Reports: GNF View - Overall Style](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2086)
* Added the Granule Not Found count, which sums the red dots in the table
* Added a border between the heading and the table

[CUMULUS-2086] GNF Report Styling

---

CHANGELOG.md
app/src/js/components/Collections/granules.js
app/src/js/components/Collections/list.js
app/src/js/components/Collections/overview.js
app/src/js/components/DropDown/dropdown.js
app/src/js/components/Executions/execution-events.js
app/src/js/components/Executions/overview.js
app/src/js/components/Granules/list.js
app/src/js/components/Granules/overview.js
app/src/js/components/Operations/overview.js
app/src/js/components/Pdr/list.js
app/src/js/components/Pdr/pdr.js
app/src/js/components/ReconciliationReports/gnf-report.js
app/src/js/components/ReconciliationReports/inventory-report.js
app/src/js/components/ReconciliationReports/list.js
app/src/js/components/ReconciliationReports/reconciliation-report.js
app/src/js/components/Rules/overview.js
app/src/js/components/Search/search.js
app/src/js/components/Workflows/overview.js
app/src/js/utils/typeahead-helpers.js
app/src/js/utils/url-helper.js
cypress/integration/collections_spec.js
cypress/integration/granules_spec.js
test/utils/url-helper.js

Addresses [CUMULUS-2021: Search Module: Search Input Fixes](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2021)
* Updates the search component to use react-bootstrap-typeahead. This is the same package we're using for for the filter dropdowns, but here we're using the async version. This gives us autocomplete functionality as well as a clear button. 
* Also added a focus handler so that text gets highlighted when clicking into it.
* Adds additional params (and documentation for those params) to <Search> for easier use with the new component
To test: perform searches across the various app pages.

[CUMULUS-2021] Update search to use typeahead component

---

CHANGELOG.md
app/src/js/actions/index.js
app/src/js/utils/format.js
cypress/integration/collections_spec.js
package-lock.json
package.json
test/actions/recover.js

Addresses [CUMULUS-2215 : Rearchitect dashboard calls for the collections list in Granule search](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2215)
* Adds request for statistics on the listCollection, and getCollection requests.
* Leaves statistics off of requests for getOptionsCollectionName, which is used on the granules overview page (and what was causing problems before)
* Adds CI test to ensure we're still displaying the statistics on the collections page.
* deletes unused code
* updates @cumulus/api for testing to @cumulus/api@3.0.2-alpha.0

Mhs/cumulus 2215/update collection api calls

---

CHANGELOG.md
app/src/js/components/Granules/overview.js
app/src/js/components/Table/Table.js
cypress/integration/granules_spec.js

**Summary:** 
Addresses [CUMULUS-2171: Dashboard's Granule overview page should provide option to download filtered granules](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2171)
* Adds `status`, `collectionId`, and `granuleIds` properties to reconciliation report request
* Collects GranuleIds based on selected granules in the granule list or, if none selected, the granule ID search filter (or selects all granules if neither are available).

Cumulus 2171 filtered granules csv

---

app/src/js/components/Granules/overview.js
cypress/integration/granules_spec.js

**Summary:** Quick fix to pass `granuleId` instead of `granuleIds` as a param when creating a Granule Inventory report. Ties into the changes from here: https://github.com/nasa/cumulus-dashboard/pull/863
Addresses [CUMULUS-2170: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-XXX)
* Pass `granuleId` instead of `granuleIds`

CUMULUS-2170 Granule inventory param

---

app/src/js/components/Granules/overview.js

Quick fix to make sure we aren't passing an empty array to the granuleId param when creating a Granule Inventory report

CUMULUS-2170-2 Fix empty granuleId array

---

cypress/integration/main_page_spec.js

In a previous PR I changed the type of errors returned in our fixture. They were previously the same. The trick in this test is that the order of the returned granules might change and the test might fail. We don't actually care about the order here, just that the two granules are listed.
* Updates 1 spec

Bugfix: Update error name in tests. 

---

CHANGELOG.md
app/src/js/components/Collections/list.js
app/src/js/components/Collections/overview.js
app/src/js/components/Executions/overview.js
app/src/js/components/Operations/overview.js
app/src/js/components/Pdr/list.js
app/src/js/components/Pdr/overview.js
app/src/js/components/Pdr/pdr.js
app/src/js/components/Providers/overview.js
app/src/js/components/Rules/overview.js
app/src/js/components/Table/Table.js
app/src/js/components/TableHeader/table-header.js
app/src/js/components/Workflows/overview.js
app/src/js/components/home.js
cypress/integration/granules_spec.js
test/components/collections/list.js
test/components/granules/overview.js
test/components/table/list-view.js

**Summary:** Clear selected when filter is applied
Addresses [CUMULUS-2245: Selected items in table not cleared when filter is applied](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2245)
* When queryParams are changed (i.e. filter are applied or removed), update `this.state.clearSelected` in `List` to true so that the table will clear the selected items. 
* Removed `dispatch` from props passed to `List` throughout the app because the `connect` higher order component already adds that as a prop.
* Updated table header area to indicate to the user how many items are selected. This made it both easier to test, and just generally makes the selected items clearer for the user.
To test:
1. Go to `/granules`
2. Select some items in the table
3. Apply a status filter
4. Verify items are no …

CUMULUS-2245 Clear selected items in table when filter is applied

---

CHANGELOG.md
app/src/js/utils/table-config/granules.js

**Summary:** 
Addresses [CUMULUS-2226: Dashboard: When user goes to page it jumps to the bottom while table loads](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2226)
We share a common component here called `ErrorReport` that is used to display errors both on the entire page as a banner and in individual table cells. In the case of the Granules table, we don't want the creation of that component to cause the screen to scroll. In other situations we would because the user needs to be drawn to the error so we're just setting the `disableScroll` flag if the component is being rendered in the table component.
* Sets `disableScroll` to `true` when rendering errors inside of the Failed Granules table

CUMULUS-2226 Disable auto-scrolling on failed granules table

---

.circleci/config.yml
CHANGELOG.md
README.md
app/src/js/config/index.js
bin/build_dashboard_image.sh
bin/build_dashboard_via_docker.sh
bin/build_docker_image.sh
bin/build_in_docker.sh
cypress/integration/granules_spec.js
docker/nginx.conf
localAPI/docker-compose-cypress.yml
package-lock.json
package.json

**Summary:** Minor CI improvements.
Addresses [CUMULUS-2242: improve dashboard experience](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2242)
* Updgrade Cypress 5.5.0
* Moves Cypress into optional dependencies.
* Excludes optional dependencies in CI and docker build shorten build times.
* Fixes nginx.config to allow redirect for react single page app.
* Stablises test via #877 (wait before selecting)
* Updates README with new quickstart information for running the docker scripts to build and create containers.
* renames helper scripts to better describe their purposes
- `./bin/build_in_docker.sh` -> `./bin/build_dashboard_via_docker.sh`
- `./bin/build_docker_image.sh` -> `./bin/build_dashboard_image.sh`

Mhs/cumulus 2242/cleanup docker builds

---

.circleci/config.yml
package.json

**Summary:** adds ability to override default port when running `npm run serve:prod` and explicitly passes AWS_REGION to override default us-west-2 in CI.
No real user facing changes.

Mhs/cumulus 2242/tweaks for running and building dashboard

---

.eslintignore
README.md
localAPI/README.md

**Summary:** capitalizes Docker.
Addresses [CUMULUS-2242: bootcamp updates](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2242)
* capitalizes Docker correctly where necessary.
* removes errant link to documentation that is to be removed
* excludes the docker/* directories from eslint.

Mhs/cumulus 2242/ Generally documentation changes found prepping for bootcamp

---

.dockerignore
CHANGELOG.md
README.md
audit-ci.json
bin/build_dashboard_image.sh
bin/build_dashboard_via_docker.sh
docker/Dockerfile
docker/docker-compose.yml

This switches the existing build scripts to use docker-compose and a new
Dockerfile that allows us to cache intermediate images.  
This doesn't litter the directories with extra files.
Addresses [CUMULUS-2242: improve Docker](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2242)
* Modernize the docker build to use a multistage container rather than a script that writes to a temp dir and runs a build command via docker.
- [ x] Update CHANGELOG
- [ na ] Unit tests
- [ x] Adhoc testing
- [ na ] Integration tests
To test, you can follow the quick start guide and ensure that you can still run ./bin/build_dashboard_via_docker.sh and ./bin/build_dashboard_image.sh as you could before.

Replace Docker scripts with multistage Dockerfile used by docker-compose

---

CHANGELOG.md
app/src/js/components/DropDown/dropdown.js
app/src/js/components/Pagination/pagination.js

Addresses [CUMULUS-2263:Dashboard: Table Header Input Interaction Tweaks](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2263)
* Updates the Pagination Typeahead input to clear when focused
* Populates the Pagination dropdown list with the appropriate page numbers
Previously a user would click the pagination input and a dropdown would appear showing only the number entered (or any page numbers starting with that number). This is a little confusing because you would either expect to see no dropdown (text input only) or a dropdown containing all available page options.
I opted to keep the dropdown but try to make it useful. Now, when a user clicks the input, the field will clear and show all available pages in the dropdown. You can select one or type any …

CUMULUS-2263 Clear pagination input on focus for cleaner UX

---

CHANGELOG.md
app/src/css/_base.scss
app/src/js/components/home.js

Addresses [CUMULUS-2070: UI fix: tables](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2070)
* added padding to the bottom of all page__content modifiers 
- [ n/a ] Update CHANGELOG
- [ n/a ] Unit tests
- [ X ] Adhoc testing
- [ n/a ] Integration tests
See Before and after PIX:

CUMULUS-2070 Adds css padding for homepage and editing collections

---

CHANGELOG.md
app/src/css/modules/_table.scss

Addresses [CUMULUS-2271: Dashboard: Table Column Horizontal Scroll
](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2271)
* Shows the overflow on table cells when hovered
Previously the only way to show the full contents of a cell was to expand the cell's width by dragging the header. You can still do that but now, if there is overflow, you can hover on a cell and a scrollbar will appear.
Note that this removes the ellipses from truncated text. We can keep it and show the "..." when text is truncated, then remove the ellipses on hover BUT then the issue is what happens when the user moves their mouse outside of the cell? I'm not sure there's a great way to keep the full, non-truncated text in that case. We can of course handle it in JS but I'm wary of …

CUMULUS-2271 Allow horizontal scrolling on table columns

---

CHANGELOG.md
app/src/js/actions/index.js
app/src/js/components/Collections/list.js
cypress/integration/collections_spec.js
test/components/collections/list.js

Addresses [CUMULUS-2270: Add provider drop down filter to Collections Overview page](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2270)
* Add provider drop down filter to Collections Overview page

CUMULUS-2270 Add provider drop down filter to Collections Overview page

---

CHANGELOG.md
app/src/css/_base.scss
app/src/css/modules/_table.scss
app/src/css/vendor/bootstrap/overrides/_card.scss
app/src/js/components/home.js

Addresses [CUMULUS-2071: Dashboard: UI Interaction Fix - Cards](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2071)
* Replaces the static Granule Updates stats on the home page with clickable cards
* Animates the Reconciliation Report > Bucket Status cards

[CUMULUS 2071] Update card interactions

---

CHANGELOG.md
app/src/css/modules/_table.scss
app/src/js/components/SortableTable/SortableTable.js
cypress/integration/granules_spec.js

**Summary:** Expand table columns
Addresses [CUMULUS-1885: Expand table columns on double click](https://bugs.earthdata.nasa.gov/browse/CUMULUS-1885)
* Column expands to fit content when double clicking the separator/resizer, which is the same behavior that is seen in excel.
* Some style tweaks. Made resizer bigger/easier to click

[CUMULUS-1885] Expand columns on double click

---

CHANGELOG.md
cypress.json
cypress/integration/auth_spec.js
cypress/integration/bulk_granules_spec.js
cypress/integration/collections_spec.js
cypress/integration/executions_spec.js
cypress/integration/granules_spec.js
cypress/integration/main_page_spec.js
cypress/integration/pdrs_spec.js
cypress/integration/providers_spec.js
cypress/integration/reconciliation_spec.js
cypress/integration/rules_spec.js
cypress/integration/workflows_spec.js
localAPI/docker-compose-cypress.yml
package-lock.json
package.json

Addresses [CUMULUS-2325: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2325)
* Migration to specs that upgrade Cypress tests to use 6.2.1
* Main changes is to replace `cy.route` & `cy.server` with `cy.intercept`.
* Followed the Migration Guide https://docs.cypress.io/guides/references/migration-guide.html#Migrating-cy-route-to-cy-intercept

Migrate to Cypress 6.2.1

---

CHANGELOG.md
app/src/css/_base.scss
app/src/css/_buttons.scss
app/src/css/_legend.scss
app/src/css/_typography.scss
app/src/css/modules/_table.scss
app/src/js/components/DropDown/dropdown.js
app/src/js/components/Executions/execution-events.js
app/src/js/components/Form/_form.scss
app/src/js/components/ListActions/ListFilters.js
app/src/js/components/ReconciliationReports/gnf-report.js
app/src/js/components/ReconciliationReports/index.js
app/src/js/components/ReconciliationReports/inventory-report.js
app/src/js/components/ReconciliationReports/legend.js
app/src/js/components/ReconciliationReports/reconciliation-report.js
app/src/js/components/ReconciliationReports/report-heading.js
app/src/js/components/Search/search.js
app/src/js/components/SortableTable/SortableTable.js
app/src/js/components/Table/TableFilters.js
app/src/js/utils/format.js
app/src/js/utils/table-config/reconciliation-reports.js
cypress/integration/reconciliation_spec.js
test/components/reconciliation-reports/reconciliation-report.js

Date range moved to same line as header
Added Total Conflict Comparisons
Download report below border
Table legend moved to Collapse component above table
Addresses [CUMULUS-2176: Reports: GNF View - Update Style & Interaction](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2176)
* Added Total Conflict Comparison section w/ description (for both GNF and Inventory)
* Removed report status
* Moved date range to be in line with header
* Made Legend collapsible and added it next to the column filters collapsible button
* Added tooltips for the colored indicators

[CUMULUS-2176] Update GNF Report Styles

---

CHANGELOG.md
app/src/js/components/ReconciliationReports/gnf-report.js
app/src/js/components/ReconciliationReports/inventory-report.js
app/src/js/components/ReconciliationReports/reconciliation-report.js
app/src/js/utils/download-file.js
app/src/js/utils/table-config/reconciliation-reports.js
cypress/fixtures/TESTCOLLECTION___006.json
cypress/integration/granules_spec.js
package-lock.json
package.json
test/components/reconciliation-reports/reconciliation-report.js

Addresses [CUMULUS-2321: reconciliationReport endpoint cannot send an "overlarge" json object](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2321)
* reconciliationReport API now returns pre-signed URL and data, so update reconciliation report to work with the API endpoint changes
* If the report data is an error message (payload size exceeds max), Inventory report and GNF pages won't be displayed, instead, the page will display error.

CUMULUS-2321: Updated reconciliation report to work with the API endpoint changes

---

CHANGELOG.md
app/src/css/modules/_table.scss
app/src/js/components/Form/_form.scss
app/src/js/components/ListActions/ListActions.js
app/src/js/components/SortableTable/SortableTable.js
app/src/js/components/Table/Table.js
app/src/js/components/Table/TableFilters.js
cypress/integration/reconciliation_spec.js

**Summary:** Add ability to show/hide columns on all tables
Addresses [CUMULUS-2297: Dashboard: Tables - Show/Hide Columns Feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2297)
* Added `TableFilters` to `List` component
* Update handling of `TableFilters` in `SortableTable` component
* Various styling changes to display column toggle in line with other buttons/actions in the `List` components

[CUMULUS-2297] Add table column toggle to all tables

---

test/reducers/api-version.js

**Summary:** The property name (`isCompatible`) was incorrect.
Addresses (no known issue)
* Fixed the property name
* Also fixed the test names

Fix version compatibility test

---

CHANGELOG.md
app/src/js/components/Granules/granule.js
app/src/js/components/Granules/list.js
app/src/js/components/Logs/viewer.js
app/src/js/components/Pdr/pdr.js
app/src/js/components/Providers/provider.js
app/src/js/reducers/execution-logs.js
app/src/js/reducers/logs.js
cypress/fixtures/execution-logs.json
cypress/integration/collections_spec.js
cypress/integration/executions_spec.js
cypress/integration/logs_spec.js
package-lock.json
package.json

Addresses [CUMULUS-2419: Dashboard doesn't display log entries for collection, granule etc.](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2419)
* Fixes log viewer query for cloud metrics log
* Cloud Metrics log doesn't parse out provider and pdrName, so only query string search can be performed.
* Update the @cumulus/api version to 7.0.0 for searching from cloud metrics log

CUMULUS-2419: Fixes log viewer query for cloud metrics log

---

CHANGELOG.md
cypress/integration/collections_spec.js
cypress/integration/executions_spec.js
cypress/integration/logs_spec.js
localAPI/docker-compose-cypress.yml
package-lock.json
package.json

**Summary:** updates cypress to 7.0.0
Addresses [CUMULUS-2282: not really](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2282)
* Upgrade cypress version
* Update matchers for cy.intercepts according to migration notes.

Upgrade to cypress 7.0.0

---

CHANGELOG.md
app/src/js/components/Executions/execution-events.js
app/src/js/utils/table-config/execution-status.js
cypress/integration/executions_spec.js
test/components/executions/execution-events.js

Addresses [CUMULUS-2435: Show Step Name in the Events table of an Execution](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2435)
* Adds step name to execution events table

[CUMULUS-2435] Add step name to execution events

---

CHANGELOG.md
app/src/css/_buttons.scss
app/src/js/components/Executions/execution-status.js
app/src/js/utils/table-config/execution-status.js
cypress/integration/executions_spec.js

Addresses [CUMULUS-2056: Updated to execution page](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2056)
* On executions Details page, Added button at bottom to go to Events
* On Events page, made task type an expandable button for step details
* On Events page, highlighted failed tasks in red

Cumulus-2056 Executions Display Improvements

---

CHANGELOG.md
app/src/js/config/index.js

Addresses [CUMULUS-2348: Implement Granule Recovery status](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2348)
* CUMULUS-2348 requires next @cumulus/api release after 8.0.0, it now uses @cumulus/api@7.2.1-alpha.0 for local API testing.

CUMULUS-2348: Version bump for next Cumulus API release

---

CHANGELOG.md
app/src/js/utils/table-config/providers.js

Addresses [CUMULUS-2604: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2604)
Very simple change which just deletes the collections column in the providers overview page

CUMULUS-2604: deleted collections column from providers

---

.gitattributes
CHANGELOG.md

-------
Addresses [CUMULUS-2616: bootcamp update](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2616)
* Adds .gitattribute file to prevent windows from changing the line endings.
https://docs.github.com/en/get-started/getting-started-with-git/configuring-git-to-handle-line-endings#per-repository-settings

Prevent windows from changing line endings.

---

CHANGELOG.md
app/src/js/components/Granules/overview.js
app/src/js/utils/table-config/granules.js
test/utils/table-config/granules.js

**Summary:** don't send undefined as a granule.
Addresses [CUMULUS-bugfix: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2576)
* Stop sending undefined granules in selectedGranules array
* Ignore granules without a published key
* test
- [X ] Update CHANGELOG
- [X ] Unit tests

Bug fix to select granules on multiple pages

---

CHANGELOG.md
localAPI/docker-compose.yml

**Summary:**
Changes docker container versions of elasticsearch from 5.6 => 5.3 to match AWS.
Addresses CUMULUS-bugfix: CI problems, but also we should just do this.

downgrade docker cluster to use elasticsearch that matches AWS version 5.3

---

CHANGELOG.md
app/src/js/components/ReconciliationReports/gnf-report.js
app/src/js/components/ReconciliationReports/inventory-report.js
app/src/js/components/ReconciliationReports/reconciliation-report.js
app/src/js/components/ReconciliationReports/reshape-report.js
app/src/js/components/SortableTable/SortableTable.js
app/src/js/utils/table-config/reconciliation-reports.js
cypress/integration/reconciliation_spec.js

Addresses [CUMULUS-2721: reconciliation reports should not have selectors and granule actions available.](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2721)
* Removes selectors and granule actions on rec report tables

[CUMULUS-2721] Remove rec report actions

---

CHANGELOG.md
app/src/js/components/Add/add.js
app/src/js/components/Form/Form.js
app/src/js/components/FormList/form-list.js
app/src/js/components/FormSchema/schema.js
app/src/js/components/Providers/add.js
cypress/integration/providers_spec.js

Addresses [CUMULUS-2747: Create Provider page should only show needed inputs based on protocol](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2747)
* Updated create provider page to only show inputs that are relevant for a particular protocol.
* SFTP is the only protocol with Private Key and Cm Key Id
* HTTP/HTTPS have Allowed Redirects and Certificate Uri
* All but S3 have Port, Username, and Password fields

[CUMULUS-2747] Show relevant create provider fields

---

package-lock.json

Fix build problem with optional dependency.

downgrade ssh2 to 1.6.0

---

CHANGELOG.md
app/src/css/utils/variables/_colors.scss
app/src/js/components/Footer/footer.js
app/src/js/components/Header/header.js
app/src/js/components/oauth.js
app/src/js/main.js
package-lock.json
package.json

**Summary:** A few Axe accessibility error fixes.
Addresses [CUMULUS-2960: Dashboard: Groom Front-end Dependencies & Errors](https://bugs.earthdata.nasa.gov/browse/CUMULUS-2960)
- Fixed the following Axe accessibility issues:
+ Specified title, level-one heading, and modal as main landmark on `/auth`
+ Increased link-background contrast in the header
+ Slight color adjustments for accessibility
- Updated dependencies with severe security vulnerabilities:
+ `@cumulus/api` to `13.1.0`
+ `moment` to `2.29.4`
+ `terser-webpack-plugin` to `5.3.3`

Axe Accessibility Fixes + Dependency Updates (from CUMULUS-2960)

---

CHANGELOG.md
app/src/js/components/Granules/bulk-granule-modal.js
app/src/js/components/Granules/bulk.js

Addresses [CUMULUS-3265: Bulk Delete not working from Cumulus dashboard](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3265)
* ...

CUMULUS-3265: Fixed bulk granule modal to correctly pass selected granules

---

CHANGELOG.md
app/src/js/actions/index.js
app/src/js/components/Granules/granule.js
cypress/integration/granules_spec.js
package-lock.json

Addresses [CUMULUS-3434: Test Cumulus v18 with ORCA release v9.0.0](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3434)
* ...

CUMULUS-3434: Fixed getGranuleRecoveryStatus action to take granuleId and collectionId

---

CHANGELOG.md
app/src/js/components/Header/header.js

Addresses [CUMULUS-3855: Dashboard: API Indicator not Displaying Information](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3855)
To ensure that API information is displayed and verified:
* Fix conditional for `useRef(mounted)`

CUMULUS-3855: Dashboard: API Indicator not Displaying Information

---

CHANGELOG.md
package-lock.json

**Summary:** NPM Audit Fix for https://github.com/advisories/GHSA-9wv6-86v2-598j and
https://github.com/advisories/GHSA-qwcr-r2fm-qrc7
Addresses [CUMULUS-3905: Develop amazing new feature](https://bugs.earthdata.nasa.gov/browse/CUMULUS-3905)
* Fix NPM audit failures:
- `body-parser`
- `path-to-regexp`

CUMULUS-3905: NPM Audit Fix

---

package-lock.json

Addresses [CUMULUS-4028: Rename cumulus-dashboard package](https://bugs.earthdata.nasa.gov/browse/CUMULUS-4028)
* Run 'npm ci' follow by 'npm install', these packages are redundant
* Removes the redundant package added by https://github.com/nasa/cumulus-dashboard/pull/1177 from https://github.com/nasa/cumulus-dashboard/pull/1176

CUMULUS-4028-2: Remove redundant packages added by dependabot

---

CHANGELOG.md
package-lock.json
package.json

Cumulus Dashboard release 13.1.0 (https://bugs.earthdata.nasa.gov/browse/CUMULUS-4021)
- Renamed cumulus-dashboard package name to `@cumulus/cumulus-dashboard`
- Upgraded axios and xml-crypto packages to fix audit issue
- Remove D3 and related libraries from dashboard.
- Updated the Dockerfile with improved NPM install command to prevent error messages.

CUMULUS-4021: Release dashboard version 13.1.0
